name: Testing

on:
  pull_request:
  issues:

jobs:
  test:
    name: Run
    runs-on: ubuntu-latest

    steps:
    - uses: TylerLeonhardt/first-interaction-pwsh@master
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
